# Generated by Django 5.1.15 on 2026-05-17 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0002_make_managed_by_nullable'),
        ('scheduling', '0002_lessonpackage_purchasedpackage_testsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('comp_type', models.CharField(choices=[('home', 'Home Competition'), ('away', 'Away Competition')], default='home', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('sanction_number', models.CharField(blank=True, max_length=50)),
                ('entry_deadline', models.DateTimeField(blank=True, null=True)),
                ('late_entry_deadline', models.DateTimeField(blank=True, null=True)),
                ('base_entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('music_upload_deadline', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.CharField(choices=[('singles', 'Singles'), ('pairs', 'Pairs'), ('dance', 'Ice Dance'), ('synchronized', 'Synchronized Skating')], default='singles', max_length=20)),
                ('segment', models.CharField(choices=[('free_skate', 'Free Skate'), ('short_program', 'Short Program'), ('moves', 'Moves in the Field'), ('pattern', 'Pattern Dance'), ('rhythm_dance', 'Rhythm Dance'), ('free_dance', 'Free Dance')], default='free_skate', max_length=20)),
                ('level', models.CharField(max_length=100)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_entries', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='competitions.competition')),
            ],
            options={
                'ordering': ['discipline', 'level', 'segment'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed (paid)'), ('accepted', 'Accepted by organizer'), ('scratched', 'Scratched')], default='draft', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_late', models.BooleanField(default=False)),
                ('music_title', models.CharField(blank=True, max_length=200)),
                ('music_artist', models.CharField(blank=True, max_length=200)),
                ('music_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('draw_number', models.IntegerField(blank=True, null=True)),
                ('skating_order', models.IntegerField(blank=True, null=True)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('scratched_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_entries', to='scheduling.coach')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='members.skater')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.eventcategory')),
            ],
            options={
                'ordering': ['competition', 'category', 'skating_order'],
            },
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['club', 'start_date', 'is_published'], name='competition_club_id_f29619_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['club', 'competition'], name='competition_club_id_45c3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionentry',
            index=models.Index(fields=['club', 'competition', 'status'], name='competition_club_id_b10b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionentry',
            index=models.Index(fields=['club', 'skater'], name='competition_club_id_5faeb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('competition', 'category', 'skater')},
        ),
    ]
