# Generated by Django 5.1.9 on 2026-05-16 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('usfs_category', models.CharField(blank=True, help_text='Exact USFS membership category string for CSV export', max_length=50)),
                ('price_in_club', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_out_of_club', models.DecimalField(decimal_places=2, help_text='Price for non-primary-club members', max_digits=8)),
                ('is_family_plan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Other / Prefer not to say')], max_length=1)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('usfs_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('membership_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('skater_stats_slug', models.CharField(blank=True, help_text="URL slug on skater-stats.com (e.g., 'emma-anderson')", max_length=100)),
                ('skater_stats_last_synced', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('medical_notes', models.TextField(blank=True)),
                ('name_pronunciation', models.CharField(blank=True, max_length=200)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skaters', to='accounts.familygroup')),
                ('managed_by', models.ForeignKey(help_text="Parent/guardian who manages this skater's account.", on_delete=django.db.models.deletion.PROTECT, related_name='managed_skaters', to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skaters', to='members.membershiptype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skater_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('registration', 'Member Registration'), ('competition_data', 'Competition History Display'), ('coach_notes', 'Coach Notes & Evaluations'), ('photo', 'Photos and Media')], max_length=30)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('consent_text', models.TextField(help_text='Exact consent text shown to user at time of consent')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_consents', to=settings.AUTH_USER_MODEL)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='members.skater')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='skater',
            index=models.Index(fields=['club', 'membership_status'], name='members_ska_club_id_6cef04_idx'),
        ),
        migrations.AddIndex(
            model_name='skater',
            index=models.Index(fields=['usfs_number'], name='members_ska_usfs_nu_10ef77_idx'),
        ),
        migrations.AddIndex(
            model_name='skater',
            index=models.Index(fields=['club', 'last_name', 'first_name'], name='members_ska_club_id_ac4808_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['skater', 'consent_type'], name='members_con_skater__17fdc1_idx'),
        ),
    ]
