# Generated by Django 5.1.15 on 2026-05-16 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='skater',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Parent/guardian for minors; null means skater manages own account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_skaters', to=settings.AUTH_USER_MODEL),
        ),
    ]
