# Generated by Django 5.1.15 on 2026-05-17 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0002_make_managed_by_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkaterLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(choices=[('moves', 'Moves in the Field'), ('freestyle', 'Freestyle'), ('dance', 'Ice Dance'), ('pairs', 'Pairs')], max_length=20)),
                ('level', models.CharField(choices=[('pre_alpha', 'Pre-Alpha'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('gamma', 'Gamma'), ('delta', 'Delta'), ('pre_juvenile', 'Pre-Juvenile'), ('juvenile', 'Juvenile'), ('intermediate', 'Intermediate'), ('novice', 'Novice'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=20)),
                ('passed_date', models.DateField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_levels', to=settings.AUTH_USER_MODEL)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='members.skater')),
            ],
            options={
                'ordering': ['discipline', 'level'],
                'indexes': [models.Index(fields=['club', 'skater'], name='members_ska_club_id_767d7a_idx')],
                'unique_together': {('skater', 'discipline')},
            },
        ),
    ]
