# Generated by Django 5.1.9 on 2026-05-16 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used for subdomain routing (e.g., 'linecreek')", unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('primary_color', models.CharField(default='#5B2C91', help_text='Hex color', max_length=7)),
                ('accent_color', models.CharField(default='#D946EF', help_text='Hex color', max_length=7)),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connected Account ID (acct_...)', max_length=100)),
                ('stripe_onboarding_complete', models.BooleanField(default=False)),
                ('current_season_start', models.DateField(blank=True, null=True)),
                ('current_season_end', models.DateField(blank=True, null=True)),
                ('season_label', models.CharField(blank=True, help_text="e.g., '2025-2026'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
