# Generated by Django 5.1.9 on 2026-05-16 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rink_location', models.CharField(blank=True, max_length=100)),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('max_bookings', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('partially_booked', 'Partially Booked'), ('fully_booked', 'Fully Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('instructor', models.ForeignKey(limit_choices_to={'role__in': ['coach', 'admin', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_slots', to=settings.AUTH_USER_MODEL)),
                ('parent_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='scheduling.instructorslot')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lesson_format', models.CharField(choices=[('private', 'Private (1-on-1)'), ('semi_private', 'Semi-Private (2-3 skaters)'), ('group', 'Group Lesson')], default='private', max_length=20)),
                ('skill_level', models.CharField(blank=True, choices=[('pre_alpha', 'Pre-Alpha'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('gamma', 'Gamma'), ('delta', 'Delta'), ('freestyle', 'Freestyle'), ('moves', 'Moves in the Field'), ('dance', 'Ice Dance'), ('all', 'All Levels')], help_text='Target USFS skill level for this lesson type', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('drop_in_price', models.DecimalField(blank=True, decimal_places=2, help_text='Drop-in price when no package is used', max_digits=8, null=True)),
                ('max_participants', models.IntegerField(default=1)),
                ('color', models.CharField(default='#5B2C91', help_text='Hex color for calendar', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_package', models.BooleanField(default=False)),
                ('allow_package', models.BooleanField(default=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('package', 'Package Used'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('client_request', 'Client Request'), ('provider_unavailable', 'Instructor Unavailable'), ('weather', 'Weather'), ('illness', 'Illness'), ('rescheduled', 'Rescheduled'), ('other', 'Other')], max_length=30)),
                ('cancellation_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('skater_notes', models.TextField(blank=True)),
                ('lesson_notes', models.TextField(blank=True, help_text="Coach's post-lesson notes")),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.instructorslot')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lesson_bookings', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_bookings_as_instructor', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='scheduling.lessonbooking')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_bookings', to='members.skater')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.lessontype')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='instructorslot',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_slots', to='scheduling.lessontype'),
        ),
        migrations.AddIndex(
            model_name='lessontype',
            index=models.Index(fields=['club', 'is_active', 'lesson_format'], name='scheduling__club_id_37dc03_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbooking',
            index=models.Index(fields=['club', 'skater', 'scheduled_date'], name='scheduling__club_id_514ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbooking',
            index=models.Index(fields=['club', 'instructor', 'scheduled_date'], name='scheduling__club_id_85953c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonbooking',
            index=models.Index(fields=['club', 'status'], name='scheduling__club_id_735b50_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorslot',
            index=models.Index(fields=['club', 'instructor', 'date'], name='scheduling__club_id_1c023e_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorslot',
            index=models.Index(fields=['club', 'date', 'status'], name='scheduling__club_id_99bf38_idx'),
        ),
    ]
