# Generated by Django 5.1.15 on 2026-05-16 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0002_make_managed_by_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, help_text='e.g. "Freestyle, Dance"', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('none', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('max_bookings', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('partially_booked', 'Partially Booked'), ('fully_booked', 'Fully Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('parent_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='scheduling.availabilityslot')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.coach')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lesson_format', models.CharField(choices=[('private', 'Private'), ('semi_private', 'Semi-Private'), ('group', 'Group'), ('test_session', 'Test Session'), ('club_ice', 'Club Ice')], default='private', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('drop_in_price', models.DecimalField(blank=True, decimal_places=2, help_text='Drop-in price when no package is used', max_digits=8, null=True)),
                ('max_participants', models.IntegerField(default=1)),
                ('color', models.CharField(default='#5B2C91', help_text='Hex color for calendar', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('cancellation_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='scheduling.availabilityslot')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='scheduling.booking')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='members.skater')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.coach')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.lessontype')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.lessontype'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['club', 'is_active'], name='scheduling__club_id_58c08d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessontype',
            index=models.Index(fields=['club', 'is_active', 'lesson_format'], name='scheduling__club_id_37dc03_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'skater', 'scheduled_date'], name='scheduling__club_id_4d3238_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'coach', 'scheduled_date'], name='scheduling__club_id_95de99_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'status'], name='scheduling__club_id_b04153_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['club', 'coach', 'date'], name='scheduling__club_id_3e011f_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['club', 'date', 'status'], name='scheduling__club_id_949a83_idx'),
        ),
    ]
