# Generated by Django 5.1.15 on 2026-05-17 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0002_make_managed_by_nullable'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lesson_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='scheduling.lessontype')),
            ],
            options={
                'ordering': ['lesson_type', 'lesson_count'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessons_total', models.IntegerField()),
                ('lessons_used', models.IntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='scheduling.lessonpackage')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_packages', to='members.skater')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('judge_name', models.CharField(blank=True, max_length=200)),
                ('test_types', models.JSONField(default=list)),
                ('fee_per_test', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('max_registrations', models.IntegerField(default=50)),
                ('is_open', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TestRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_types', models.JSONField(default=list)),
                ('test_levels', models.JSONField(default=dict)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('registered', 'Registered'), ('pass', 'Pass'), ('retry', 'Retry'), ('scratch', 'Scratched')], default='registered', max_length=20)),
                ('result_notes', models.TextField(blank=True)),
                ('scratched_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_registrations', to='members.skater')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='scheduling.testsession')),
            ],
            options={
                'ordering': ['skater__last_name', 'skater__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonpackage',
            index=models.Index(fields=['club', 'lesson_type', 'is_active'], name='scheduling__club_id_6ae6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedpackage',
            index=models.Index(fields=['club', 'skater', 'payment_status'], name='scheduling__club_id_2fdf53_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['club', 'date', 'is_open'], name='scheduling__club_id_0c3a97_idx'),
        ),
        migrations.AddIndex(
            model_name='testregistration',
            index=models.Index(fields=['club', 'test_session'], name='scheduling__club_id_8271dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testregistration',
            unique_together={('test_session', 'skater')},
        ),
    ]
