# Generated by Django 5.1.15 on 2026-05-17 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('members', '0003_skaterlevel'),
        ('scheduling', '0002_lessonpackage_purchasedpackage_testsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_date', models.DateField()),
                ('skating_skills', models.IntegerField(blank=True, null=True)),
                ('transitions', models.IntegerField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('choreography', models.IntegerField(blank=True, null=True)),
                ('interpretation', models.IntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_to_improve', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('overall_notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='scheduling.coach')),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='members.skater')),
            ],
            options={
                'ordering': ['-evaluation_date'],
                'indexes': [models.Index(fields=['club', 'skater', 'evaluation_date'], name='scheduling__club_id_3f334e_idx')],
            },
        ),
    ]
